[workspace]
authors = ["JakeKitzmann <97077033+JakeKitzmann@users.noreply.github.com>"]
channels = ["conda-forge"]
name = "PCCTAirwaySegmentation"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]
build = { cmd = "cmake .. -DITK_DIR=~/dev/ITK-build -DSlicerExecutionModel_DIR=~/dev/SEM-build && cmake --build .", cwd = "build" }
test = { cmd = "./RunRegistration --imgLow ../../../TestData/Test256.nii.gz --imgHigh ../../../TestData/Test512.nii.gz --airwaySegLow ../../../TestData/Mask256.nii.gz", cwd = "build/GroundTruthRegistration/src" }

[dependencies]
python = ">=3.14.5,<3.15"
matplotlib = ">=3.10.9,<4"
numpy = ">=2.4.6,<3"
pandas = ">=3.0.3,<4"
ipykernel = ">=7.2.0,<8"
jupyterlab = ">=4.5.8,<5"
simpleitk = ">=2.5.5,<3"
gdown = ">=6.1.0,<7"

[pypi-dependencies]
itk = ">=5.4.6, <6"
